In [1]:
import torch

In [2]:
# broadcasting example 1
a = torch.ones(5, 1)     # shape (5, 1)
b = torch.ones(1, 4)     # shape (1, 4)
c = a + b                # result shape (5, 4)
print(c.shape)
print(c)

torch.Size([5, 4])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])


In [3]:
a =     torch.ones(4, 3, 2)
# Tensor b has 3rd & 2nd dims identical to a, dim 1 absent
b = a * torch.rand(   3, 2) 
print(b.shape)
print(b)

torch.Size([4, 3, 2])
tensor([[[0.5117, 0.7781],
         [0.1607, 0.5141],
         [0.0924, 0.3007]],

        [[0.5117, 0.7781],
         [0.1607, 0.5141],
         [0.0924, 0.3007]],

        [[0.5117, 0.7781],
         [0.1607, 0.5141],
         [0.0924, 0.3007]],

        [[0.5117, 0.7781],
         [0.1607, 0.5141],
         [0.0924, 0.3007]]])


In [4]:
# Tensor c has 3rd dim = 1, 2nd dim identical to a
c = a * torch.rand(   3, 1)
print(c.shape)
print(c)

torch.Size([4, 3, 2])
tensor([[[0.7560, 0.7560],
         [0.4111, 0.4111],
         [0.1826, 0.1826]],

        [[0.7560, 0.7560],
         [0.4111, 0.4111],
         [0.1826, 0.1826]],

        [[0.7560, 0.7560],
         [0.4111, 0.4111],
         [0.1826, 0.1826]],

        [[0.7560, 0.7560],
         [0.4111, 0.4111],
         [0.1826, 0.1826]]])


In [ ]:
# Tensor d has 3rd dim identical to a, 2nd dim = 1
d = a * torch.rand(   1, 2)
print(d.shape)
print(d)

In [5]:
# numpy bridge from numpy to tensor
import numpy as np
numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)


[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [6]:
# reverse example from tensor to numpy
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)


tensor([[0.8530, 0.5607, 0.8721],
        [0.5790, 0.1472, 0.7754]])
[[0.85303164 0.56073594 0.87208575]
 [0.5789896  0.14721131 0.77543503]]


In [7]:
# connected changes 
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)


tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.85303164  0.56073594  0.87208575]
 [ 0.5789896  17.          0.77543503]]
